id: AFD2D555F
title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great Perfection’s
  Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
type: translation
pechas:
- I41EBF94E
- I488E8688
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:42:19.006468
  last_modified_at: 2023-01-04 12:42:19.006486
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I41EBF94E/6AE4: 819E
  I488E8688/02D8: 819E
